.github/workflows/build.yml
.github/workflows/mutation.yml
README.md
composer.json
psalm.xml
src/RoadRunnerApplicationRunner.php

Cleanup, update dependencies, raise psalm error level

---

src/RoadRunnerApplicationRunner.php

Add ability to set a temporary error handler

---

composer.json
src/RoadRunnerApplicationRunner.php

| Breaks BC?    | ✔️
Waiting: https://github.com/yiisoft/yii-http/pull/1

Use yiisoft/yii-http as dependency instead of yiisoft/yii-web

---

README.md
src/RoadRunnerApplicationRunner.php

| New feature?  |  ❌
| Breaks BC?    | ✔️
Waiting:
https://github.com/yiisoft/yii-http/pull/2
https://github.com/yiisoft/yii-runner/pull/4

Change ThrowableHandler namespace due transfer to yii-http

---

src/RoadRunnerApplicationRunner.php

Add docblocks for classes and methods

---

src/RoadRunnerApplicationRunner.php

| Is bugfix?    | ✔️
| Fixed issues  | https://github.com/yiisoft/di/pull/276

Adapt to DI changes

---

README.md

| Fixed issues  | Wrong namespace

Fix namespace

---

src/RoadRunnerApplicationRunner.php

| Fixed issues  |  -
Waiting: https://github.com/yiisoft/yii-runner/pull/6

Update RoadRunnerApplicationRunner due improve ConfigFactory::create()

---

composer.json
src/RoadRunnerApplicationRunner.php

Replace use of Config instance to ConfigInterface

---

.github/workflows/build.yml
README.md
composer.json
psalm.xml
src/RoadRunnerApplicationRunner.php

| Breaks BC?    | ✔️
Waiting: https://github.com/yiisoft/yii-runner/pull/9

Update due yiisoft/yii-runner changes and update readme

---

src/RoadRunnerApplicationRunner.php
tests/RoadRunnerApplicationRunnerTest.php
tests/RoadRunnerWorkerTest.php

Minor naming corrections

---

.github/workflows/build.yml
CHANGELOG.md
composer.json

| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌

Update `psr/log` version

---

CHANGELOG.md
composer.json

Update yiisoft/log-target-file version

---

tests/Support/config/web.php
tests/TestCase.php

| Is bugfix?    | ✔️
| Fixed issues  | Related - https://github.com/yiisoft/middleware-dispatcher/pull/55

Sync with middleware dispatcher changes

---

README.md

| Is bugfix?    | ✔️
| Fixed issues  | 
Fixed roadrunner launch and updated the configuration to a working one.

Updated configuration example

---

README.md

| Is bugfix?    | ✔️
| Fixed issues  | https://github.com/yiisoft/yii-runner-roadrunner/pull/57#issuecomment-1472008454
The fixes are important for RoadRunner 2023.1 that will be released tomorrow

Fix rr.yml example

---

README.md
docs/en/README.md
docs/ru/README.md

Added docs links

---

CHANGELOG.md
composer.json

Add support for `psr/http-message` of `^2.0` version

---

.github/workflows/mutation.yml

Fix mutation testing

---

.github/workflows/bc.yml
.github/workflows/build.yml
.github/workflows/composer-require-checker.yml
CHANGELOG.md

Fix changelog + Improve CI
